### ISSUE TITLE
Automatické publikování gh-pages

### ISSUE THREAD

**Issue by kreuzter** [fSkripta/fSkripta#3]
Bylo by skvělé, kdyby se při každém `git push` automaticky provedl build a aktualizovaná fSkripta se publikovala sama. Myslim, že [tento projekt](https://github.com/ammaraskar/sphinx-action-test) je dobrý minimální příklad. Pokud se nepletu, je omezený počet provedených "actions" (v našem případě buildů) za den, ale to nás příliš netrápí. Push se zase tak často nedělá.

**Comment by fSkripta** [comment]
Solved by fcf4a8c7d661ce84c9242e9e7f3cdb5a3a6e3b31
